/**
 * Accessibility statement generator.
 *
 * Generates a public accessibility statement page. This is what you
 * publish at /accessibility (or /a11y) — it tells users what level
 * of conformance you target, known issues, and how to report
 * accessibility problems.
 *
 * It's not a substitute for actually being accessible, but it's the
 * standard mitigation for ADA / EAA / AODA compliance gaps and it
 * demonstrates good faith effort to users with disabilities.
 */

export interface AccessibilityStatementInput {
  projectName: string;
  contactEmail: string;
  /** Conformance target — defaults to WCAG 2.1 AA */
  standard?: string;
}

export function generateAccessibilityStatement(
  input: AccessibilityStatementInput
): { path: string; content: string } {
  const standard = input.standard || "WCAG 2.1 Level AA";
  const date = new Date().toISOString().slice(0, 10);

  return {
    path: "ACCESSIBILITY.md",
    content: `# Accessibility Statement for ${input.projectName}

_Last updated: ${date}_

${input.projectName} is committed to making our website accessible to everyone, including people with disabilities. We believe that everyone deserves equal access to information and functionality on the web.

## Conformance Standard

We aim to conform to **${standard}** — the international standard for web accessibility published by the W3C.

This includes:
- **Perceivable**: Text alternatives for images, captions for video, sufficient color contrast
- **Operable**: Keyboard navigation, no content that causes seizures, clear page titles
- **Understandable**: Readable text, predictable behavior, input assistance
- **Robust**: Compatible with assistive technologies like screen readers

## What We've Done

- All interactive elements are keyboard-accessible
- All images have descriptive alt text
- All form fields have associated labels
- Color contrast meets AA standards (4.5:1 for body text, 3:1 for large text)
- The site works at 200% browser zoom without horizontal scrolling
- We use semantic HTML (headings, landmarks, lists)

## Known Limitations

Despite our efforts, some content may not yet be fully accessible. We're actively working to improve this. Known issues include:

- Some older PDF documents may not be fully tagged for screen readers
- Some user-generated content (comments, uploads) may not have alt text
- Some third-party widgets may not be fully accessible

If you encounter an accessibility barrier, please let us know.

## Reporting Accessibility Issues

If you have difficulty accessing any part of ${input.projectName}, please contact us:

**Email**: ${input.contactEmail}

We aim to respond to accessibility feedback within 2 business days and to propose a solution within 10 business days.

## Enforcement

If you're not satisfied with our response, you can contact the relevant enforcement body in your jurisdiction:

- **EU/EEA/UK**: Your national enforcement authority
- **United States**: Department of Justice ADA complaints
- **Canada**: Canadian Human Rights Commission
- **Australia**: Australian Human Rights Commission

---

> This accessibility statement is auto-generated by ShipReady based on ${input.projectName}'s stated WCAG target. It's a starting point, not a legal document. Consult an accessibility specialist for production compliance.
`,
  };
}
