/**
 * Cookie consent banner generator.
 *
 * Generates a GDPR-compliant cookie consent banner component that:
 *   - Shows a banner when the user first visits the site
 *   - Lets users accept or reject non-essential cookies
 *   - Stores the preference in localStorage
 *   - Has a "cookie settings" button to reopen the banner
 *
 * For Next.js / Remix: generates `app/components/cookie-consent.tsx` (a "use client" component)
 * For all other frameworks: generates `public/cookie-consent-snippet.html` (paste-into-head snippet)
 *
 * Generated alongside COOKIES.md when the project uses cookies.
 */

import type { Framework } from "../framework";

export interface CookieConsentBannerInput {
  framework: Framework;
  projectName: string;
  /** Whether the project serves EU users (triggers explicit consent requirement) */
  servesEuUsers?: boolean;
}

/**
 * Generate a cookie consent banner file.
 */
export function generateCookieConsentBanner(
  input: CookieConsentBannerInput
): { path: string; content: string } {
  if (input.framework === "nextjs" || input.framework === "remix") {
    return generateNextjsBanner(input);
  }

  return generateStaticBanner(input);
}

function generateNextjsBanner(input: CookieConsentBannerInput): {
  path: string;
  content: string;
} {
  const gdprLine = input.servesEuUsers
    ? "\n *   - Meets GDPR / ePrivacy consent requirements"
    : "";

  const component = [
    '"use client";',
    "",
    'import { useState, useEffect } from "react";',
    "",
    "/**",
    " * Cookie consent banner for " + input.projectName + ".",
    " * Auto-generated by ShipReady.",
    " *",
    " * Usage: Add <CookieConsent /> to your root layout (app/layout.tsx).",
    " *",
    " * Features:",
    " *   - Shows banner on first visit",
    " *   - Stores user preference in localStorage",
    " *   - \"Accept\" enables all cookies",
    ' *   - "Reject" disables non-essential cookies' + gdprLine,
    ' *   - Small floating "Cookie settings" button to re-open the banner',
    " */",
    "export function CookieConsent() {",
    '  const [show, setShow] = useState(false);',
    '  const [preference, setPreference] = useState<"accepted" | "rejected" | null>(null);',
    "",
    "  useEffect(() => {",
    '    const stored = localStorage.getItem("cookie-consent");',
    '    if (stored === "accepted" || stored === "rejected") {',
    "      setPreference(stored);",
    "      applyConsent(stored);",
    "    } else {",
    "      const timer = setTimeout(() => setShow(true), 500);",
    "      return () => clearTimeout(timer);",
    "    }",
    "  }, []);",
    "",
    "  function acceptAll() {",
    '    localStorage.setItem("cookie-consent", "accepted");',
    '    setPreference("accepted");',
    "    setShow(false);",
    '    applyConsent("accepted");',
    "  }",
    "",
    "  function rejectAll() {",
    '    localStorage.setItem("cookie-consent", "rejected");',
    '    setPreference("rejected");',
    "    setShow(false);",
    '    applyConsent("rejected");',
    "  }",
    "",
    "  function openSettings() {",
    "    setShow(true);",
    "  }",
    "",
    "  if (!show && preference) {",
    "    return (",
    "      <button",
    "        onClick={openSettings}",
    '        aria-label="Cookie settings"',
    "        style={{",
    '          position: "fixed",',
    '          bottom: "1rem",',
    '          left: "1rem",',
    "          zIndex: 9999,",
    '          padding: "0.5rem 0.75rem",',
    '          fontSize: "0.75rem",',
    '          background: "#0a0a09",',
    '          color: "#fafaf9",',
    '          border: "1px solid #292524",',
    '          borderRadius: "0.5rem",',
    '          cursor: "pointer",',
    '          fontFamily: "system-ui, -apple-system, sans-serif",',
    "          opacity: 0.85,",
    "        }}",
    "      >",
    '        Cookie settings',
    "      </button>",
    "    );",
    "  }",
    "",
    "  if (!show) return null;",
    "",
    "  return (",
    '    <div role="dialog" aria-label="Cookie consent" aria-modal="true"',
    "      style={{",
    '        position: "fixed", bottom: 0, left: 0, right: 0,',
    "        zIndex: 10000, padding: \"1rem 1.5rem\",",
    '        background: "#0a0a09", borderTop: "1px solid #292524",',
    '        fontFamily: "system-ui, -apple-system, sans-serif",',
    "      }}",
    "    >",
    '      <div style={{',
    '        maxWidth: "64rem", margin: "0 auto",',
    "        display: \"flex\", alignItems: \"center\",",
    "        justifyContent: \"space-between\", gap: \"1rem\", flexWrap: \"wrap\",",
    "      }},",
    '        <p style={{ margin: 0, fontSize: "0.875rem", color: "#a8a29e", lineHeight: 1.5 }}>',
    "          We use cookies to improve your experience, analyze traffic,",
    "          and serve personalized content. You can choose which cookies to allow.",
    "        </p>",
    '        <div style={{ display: "flex", gap: "0.5rem", flexShrink: 0 }}>',
    "          <button onClick={rejectAll} style={{",
    '            padding: "0.5rem 1rem", fontSize: "0.8125rem",',
    '            background: "transparent", color: "#a8a29e",',
    '            border: "1px solid #292524", borderRadius: "0.375rem",',
    '            cursor: "pointer", fontWeight: 500,',
    "          }}>Reject all</button>",
    "          <button onClick={acceptAll} style={{",
    '            padding: "0.5rem 1rem", fontSize: "0.8125rem",',
    '            background: "#c4f542", color: "#0a0a09",',
    '            border: "none", borderRadius: "0.375rem",',
    '            cursor: "pointer", fontWeight: 600,',
    "          }}>Accept all</button>",
    "        </div>",
    "      </div>",
    "    </div>",
    "  );",
    "}",
    "",
    "/** Apply consent preference as cookie + dispatch event. */",
    'function applyConsent(preference: "accepted" | "rejected") {',
    '  document.cookie = "cookie-consent=" + preference + "; path=/; max-age=31536000; SameSite=Lax";',
    '  window.dispatchEvent(new CustomEvent("cookieConsentChange", { detail: { preference } }));',
    "}",
  ].join("\n");

  return {
    path: "app/components/cookie-consent.tsx",
    content: component,
  };
}

function generateStaticBanner(input: CookieConsentBannerInput): {
  path: string;
  content: string;
} {
  return {
    path: "public/cookie-consent-snippet.html",
    content: [
      "<!-- Cookie consent banner for " + input.projectName + " -->",
      "<!-- Auto-generated by ShipReady. Paste this before the closing </body> tag. -->",
      "",
      '<div id="cookie-consent-banner" style="',
      "  position: fixed; bottom: 0; left: 0; right: 0; z-index: 10000;",
      '  padding: 1rem 1.5rem; background: #0a0a09; border-top: 1px solid #292524;',
      '  font-family: system-ui, -apple-system, sans-serif;',
      '">',
      '  <div style="max-width: 64rem; margin: 0 auto; display: flex;',
      "    align-items: center; justify-content: space-between; gap: 1rem;",
      '    flex-wrap: wrap;">',
      '    <p style="margin: 0; font-size: 0.875rem; color: #a8a29e; line-height: 1.5;">',
      "      We use cookies to improve your experience, analyze traffic,",
      "      and serve personalized content. You can choose which cookies to allow.",
      "    </p>",
      '    <div style="display: flex; gap: 0.5rem; flex-shrink: 0;">',
      '      <button onclick="rejectCookies()" style="',
      "        padding: 0.5rem 1rem; font-size: 0.8125rem;",
      "        background: transparent; color: #a8a29e;",
      '        border: 1px solid #292524; border-radius: 0.375rem;',
      '        cursor: pointer; font-weight: 500;">Reject all</button>',
      '      <button onclick="acceptCookies()" style="',
      "        padding: 0.5rem 1rem; font-size: 0.8125rem;",
      "        background: #c4f542; color: #0a0a09;",
      '        border: none; border-radius: 0.375rem;',
      '        cursor: pointer; font-weight: 600;">Accept all</button>',
      "    </div>",
      "  </div>",
      "</div>",
      "",
      '<button id="cookie-settings-btn" style="',
      "  position: fixed; bottom: 1rem; left: 1rem; z-index: 9999;",
      "  padding: 0.5rem 0.75rem; font-size: 0.75rem;",
      "  background: #0a0a09; color: #fafaf9;",
      '  border: 1px solid #292524; border-radius: 0.5rem;',
      "  cursor: pointer; font-family: system-ui, -apple-system, sans-serif;",
      '  display: none;">Cookie settings</button>',
      "",
      "<script>",
      "(function() {",
      '  var banner = document.getElementById("cookie-consent-banner");',
      '  var settingsBtn = document.getElementById("cookie-settings-btn");',
      '  var preference = localStorage.getItem("cookie-consent");',
      "",
      '  if (preference === "accepted" || preference === "rejected") {',
      '    banner.style.display = "none";',
      '    settingsBtn.style.display = "block";',
      "    applyConsent(preference);",
      "  }",
      "",
      "  window.acceptCookies = function() {",
      '    localStorage.setItem("cookie-consent", "accepted");',
      '    banner.style.display = "none";',
      '    settingsBtn.style.display = "block";',
      '    applyConsent("accepted");',
      "  };",
      "",
      "  window.rejectCookies = function() {",
      '    localStorage.setItem("cookie-consent", "rejected");',
      '    banner.style.display = "none";',
      '    settingsBtn.style.display = "block";',
      '    applyConsent("rejected");',
      "  };",
      "",
      '  settingsBtn.addEventListener("click", function() {',
      '    banner.style.display = "block";',
      '    settingsBtn.style.display = "none";',
      "  });",
      "",
      "  function applyConsent(pref) {",
      '    document.cookie = "cookie-consent=" + pref + "; path=/; max-age=31536000; SameSite=Lax";',
      '    window.dispatchEvent(new CustomEvent("cookieConsentChange", { detail: { preference: pref } }));',
      "  }",
      "})();",
      "</script>",
    ].join("\n"),
  };
}
