/**
 * Cookie policy generator.
 *
 * Two paths:
 *   1. AI path (when `codebase` is provided and AI is enabled)
 *   2. Static path (default)
 *
 * Only generated when context.usesCookies is true.
 */

import type { ProjectContext, CodebaseContext } from "../types";
import { generateCookiePolicyWithAI } from "./_ai-prompts";
import { aiEnabled } from "@/lib/ai";

export interface CookiePolicyInput {
  context: ProjectContext;
  projectName: string;
  contactEmail: string;
  effectiveDate?: string;
  /** Optional: AI-curated codebase context. */
  codebase?: CodebaseContext;
}

export async function generateCookiePolicy(input: CookiePolicyInput): Promise<string> {
  // AI path
  if (input.codebase && aiEnabled) {
    const aiResult = await generateCookiePolicyWithAI({
      projectName: input.projectName,
      contactEmail: input.contactEmail,
      projectContext: input.context,
      codebase: input.codebase,
      effectiveDate: input.effectiveDate,
    });
    if (aiResult.ok) {
      return aiResult.text;
    }
    // Fall through to static
  }

  return generateCookiePolicyStatic(input);
}

/**
 * Static (non-AI) cookie policy generator.
 */
export function generateCookiePolicyStatic(input: CookiePolicyInput): string {
  const ctx = input.context;
  const date = input.effectiveDate || new Date().toISOString().slice(0, 10);

  return `# Cookie Policy

_Last updated: ${date}_

This Cookie Policy explains how **${input.projectName}** ("we", "our", "us") uses cookies and similar technologies when you visit our website. It should be read together with our Privacy Policy.

## What Are Cookies?

Cookies are small text files that are stored on your device when you visit a website. They are widely used to make websites work more efficiently and to provide information to website operators.

We also use similar technologies such as **local storage**, **session storage**, and **pixels/tracking tags**, which serve similar purposes.

## What Cookies Do We Use?

We use the following categories of cookies on our website:

### Strictly Necessary Cookies

These cookies are essential to provide you with the Service and cannot be switched off. They are usually set in response to actions you take, such as logging in, filling forms, or setting your privacy preferences.

- **Authentication cookies**: Keep you logged in
- **Security cookies**: Protect against fraud and abuse
- **Load-balancing cookies**: Direct your request to the right server

### Analytics Cookies

These cookies allow us to count visits and traffic sources so we can measure and improve the performance of the Service. They help us understand which pages are the most and least popular and see how visitors move around the site.

${ctx.usesCookies ? "All information collected by analytics cookies is aggregated and anonymous." : ""}

### Functionality Cookies

These cookies enable enhanced functionality and personalization, such as remembering your preferences (language, region) and providing improved features.

## Third-Party Cookies

Some cookies on our website are set by third-party services we use. These may include:

- **Analytics providers** (e.g., Plausible, Google Analytics): Help us understand usage patterns
${ctx.processesPayments ? "- **Payment processors** (e.g., Stripe): Required to process transactions securely\n" : ""}- **Embedded content**: Pages may include content from other websites (e.g., YouTube, Twitter), which may set their own cookies

## How to Manage Cookies

You can control and manage cookies in several ways:

**Browser settings**: Most browsers allow you to refuse cookies, delete existing cookies, or receive a warning before a cookie is stored. Refer to your browser's help documentation for instructions.

${ctx.servesEuUsers ? "**Consent banner**: For users in the EEA/UK, we display a cookie consent banner on your first visit. You can change your preferences at any time by clicking the \"Cookie settings\" link in the website footer." : ""}

**Opt-out tools**: For analytics cookies, you can use opt-out tools provided by the analytics service (e.g., the [Google Analytics Opt-out Browser Add-on](https://tools.google.com/dlpage/gaoptout)).

Please note that disabling certain cookies may affect the functionality of the Service.

## Changes to This Cookie Policy

We may update this Cookie Policy from time to time. When we do, we will revise the "Last updated" date at the top. If the changes are material, we will provide more prominent notice.

## Contact

If you have any questions about our use of cookies, please contact us at **${input.contactEmail}**.

---

_Generated by [ShipReady](https://shipready.dev) · This is a template, not legal advice._
`;
}
