/**
 * Error page generators for Next.js App Router.
 *
 * Generates:
 *   - app/not-found.tsx     — custom 404 page
 *   - app/error.tsx         — error boundary for route segments
 *   - app/global-error.tsx  — catches errors in the root layout itself
 *
 * All three use the same ShipReady design language: serif display headline,
 * accent color on a number, clear CTAs back to working pages.
 *
 * These are only generated for Next.js (and Remix, which uses the same
 * conventions). For Astro / Vite, we ship static 404.html / 500.html.
 */

export interface ErrorPageInput {
  projectName: string;
  siteUrl?: string;
}

export function generateNotFound(input: ErrorPageInput): { path: string; content: string } {
  return {
    path: "app/not-found.tsx",
    content: `import Link from "next/link";

/**
 * Custom 404 page for ${input.projectName}.
 * Auto-generated by ShipReady. Edit the copy to match your brand voice.
 */
export default function NotFound() {
  return (
    <main className="min-h-screen flex items-center justify-center px-6">
      <div className="max-w-md text-center">
        <p className="font-mono text-sm text-foreground-dim mb-4">404</p>
        <h1 className="font-display text-5xl tracking-tight mb-4">
          Page not found
        </h1>
        <p className="text-foreground-muted mb-8 leading-relaxed">
          The page you're looking for doesn't exist or has been moved.
          It might also be a broken link from another site.
        </p>
        <div className="flex gap-3 justify-center">
          <Link
            href="/"
            className="px-4 py-2 rounded-lg bg-accent text-accent-foreground font-medium hover:brightness-110 transition-all"
          >
            Back to home
          </Link>
          <Link
            href="/blog"
            className="px-4 py-2 rounded-lg border border-border hover:bg-background-elevated transition-all"
          >
            Read the blog
          </Link>
        </div>
      </div>
    </main>
  );
}
`,
  };
}

export function generateErrorPage(input: ErrorPageInput): { path: string; content: string } {
  return {
    path: "app/error.tsx",
    content: `"use client";

import { useEffect } from "react";
import Link from "next/link";

/**
 * Error boundary for ${input.projectName}.
 * Auto-generated by ShipReady. This catches unhandled exceptions in any
 * route segment. Customize the message, then make sure you're reporting
 * errors to Sentry / PostHog / your own logger.
 */
export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  useEffect(() => {
    // TODO: send to your error reporting service
    // e.g. Sentry.captureException(error);
    console.error(error);
  }, [error]);

  return (
    <main className="min-h-screen flex items-center justify-center px-6">
      <div className="max-w-md text-center">
        <p className="font-mono text-sm text-foreground-dim mb-4">500</p>
        <h1 className="font-display text-5xl tracking-tight mb-4">
          Something went wrong
        </h1>
        <p className="text-foreground-muted mb-8 leading-relaxed">
          We hit an unexpected error. The team has been notified. Try again,
          or come back in a few minutes.
        </p>
        {error.digest && (
          <p className="font-mono text-xs text-foreground-dim mb-4">
            ref: {error.digest}
          </p>
        )}
        <div className="flex gap-3 justify-center">
          <button
            onClick={reset}
            className="px-4 py-2 rounded-lg bg-accent text-accent-foreground font-medium hover:brightness-110 transition-all"
          >
            Try again
          </button>
          <Link
            href="/"
            className="px-4 py-2 rounded-lg border border-border hover:bg-background-elevated transition-all"
          >
            Back to home
          </Link>
        </div>
      </div>
    </main>
  );
}
`,
  };
}

export function generateGlobalError(input: ErrorPageInput): { path: string; content: string } {
  return {
    path: "app/global-error.tsx",
    content: `"use client";

/**
 * Global error boundary for ${input.projectName}.
 * Auto-generated by ShipReady. This is the LAST line of defense — it
 * catches errors that happen in the root layout itself, where error.tsx
 * can't reach. Must include its own <html> and <body> tags.
 *
 * Docs: https://nextjs.org/docs/app/api-reference/file-conventions/error#global-error
 */
export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  return (
    <html lang="en">
      <body
        style={{
          minHeight: "100vh",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          padding: "1.5rem",
          background: "#0a0a09",
          color: "#fafaf9",
          fontFamily: "system-ui, -apple-system, sans-serif",
        }}
      >
        <div style={{ maxWidth: "28rem", textAlign: "center" }}>
          <p
            style={{
              fontFamily: "monospace",
              fontSize: "0.875rem",
              color: "#a8a29e",
              marginBottom: "1rem",
            }}
          >
            Critical error
          </p>
          <h1
            style={{
              fontSize: "2.25rem",
              fontWeight: 600,
              marginBottom: "1rem",
            }}
          >
            Something broke
          </h1>
          <p
            style={{
              color: "#a8a29e",
              marginBottom: "2rem",
              lineHeight: 1.6,
            }}
          >
            The site hit an unrecoverable error. Try refreshing the page.
            If it keeps happening, contact support.
          </p>
          {error.digest && (
            <p
              style={{
                fontFamily: "monospace",
                fontSize: "0.75rem",
                color: "#78716c",
                marginBottom: "1rem",
              }}
            >
              ref: {error.digest}
            </p>
          )}
          <button
            onClick={reset}
            style={{
              padding: "0.5rem 1rem",
              background: "#c4f542",
              color: "#0a0a09",
              border: "none",
              borderRadius: "0.5rem",
              fontWeight: 500,
              cursor: "pointer",
            }}
          >
            Try again
          </button>
        </div>
      </body>
    </html>
  );
}
`,
  };
}
