/**
 * Error page generators — framework-aware.
 *
 * Generates:
 *   - 404 / not-found page
 *   - Error boundary / 500 page
 *   - Global error (Next.js only)
 *
 * Framework dispatch:
 *   - Next.js / Remix: app/not-found.tsx, app/error.tsx, app/global-error.tsx
 *   - Astro: src/pages/404.astro, src/pages/500.astro
 *   - SvelteKit: src/routes/+error.svelte (single page handles both 404 + 500)
 *   - Vite / unknown: static public/404.html, public/500.html
 */

import type { Framework } from "../framework";

export interface ErrorPageInput {
  projectName: string;
  siteUrl?: string;
  framework: Framework;
}

/** Check if framework uses Next.js-style App Router conventions. */
function hasAppRouter(framework: Framework): boolean {
  return framework === "nextjs" || framework === "remix";
}

/** Check if framework uses SvelteKit conventions. */
function isSvelteKit(framework: Framework): boolean {
  return framework === "sveltekit";
}

/** Check if framework is Astro. */
function isAstro(framework: Framework): boolean {
  return framework === "astro";
}

// ─────────────────────────────────────────────────────────────
//  404 / Not Found
// ─────────────────────────────────────────────────────────────

export function generateNotFound(input: ErrorPageInput): { path: string; content: string } {
  if (hasAppRouter(input.framework)) {
    return generateNotFoundNextjs(input);
  }
  if (isAstro(input.framework)) {
    return generateNotFoundAstro(input);
  }
  if (isSvelteKit(input.framework)) {
    return generateNotFoundSvelteKit(input);
  }
  // Vite / unknown — static HTML
  return generateNotFoundStatic(input);
}

function generateNotFoundNextjs(input: ErrorPageInput) {
  return {
    path: "app/not-found.tsx",
    content: `import Link from "next/link";

/**
 * Custom 404 page for ${input.projectName}.
 * Auto-generated by ShipReady. Edit the copy to match your brand voice.
 */
export default function NotFound() {
  return (
    <main className="min-h-screen flex items-center justify-center px-6">
      <div className="max-w-md text-center">
        <p className="font-mono text-sm text-foreground-dim mb-4">404</p>
        <h1 className="font-display text-5xl tracking-tight mb-4">
          Page not found
        </h1>
        <p className="text-foreground-muted mb-8 leading-relaxed">
          The page you&apos;re looking for doesn&apos;t exist or has been moved.
        </p>
        <div className="flex gap-3 justify-center">
          <Link
            href="/"
            className="px-4 py-2 rounded-lg bg-accent text-accent-foreground font-medium hover:brightness-110 transition-all"
          >
            Back to home
          </Link>
        </div>
      </div>
    </main>
  );
}
`,
  };
}

function generateNotFoundAstro(input: ErrorPageInput) {
  return {
    path: "src/pages/404.astro",
    content: `---
/**
 * Custom 404 page for ${input.projectName}.
 * Auto-generated by ShipReady.
 */
const siteUrl = "${input.siteUrl || `https://${input.projectName.toLowerCase()}.com`}";
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>404 — ${input.projectName}</title>
    <link rel="canonical" href=\`\${siteUrl}/404\` />
  </head>
  <body>
    <main style="
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 1.5rem;
      font-family: system-ui, -apple-system, sans-serif;
      background: #0a0a09;
      color: #fafaf9;
    ">
      <div style="max-width: 28rem; text-align: center;">
        <p style="font-family: monospace; font-size: 0.875rem; color: #a8a29e; margin-bottom: 1rem;">404</p>
        <h1 style="font-size: 2.25rem; font-weight: 600; margin-bottom: 1rem;">Page not found</h1>
        <p style="color: #a8a29e; margin-bottom: 2rem; line-height: 1.6;">
          The page you&apos;re looking for doesn&apos;t exist or has been moved.
        </p>
        <a href="/" style="
          display: inline-block;
          padding: 0.5rem 1rem;
          background: #c4f542;
          color: #0a0a09;
          border-radius: 0.5rem;
          font-weight: 500;
          text-decoration: none;
        ">
          Back to home
        </a>
      </div>
    </main>
  </body>
</html>
`,
  };
}

function generateNotFoundSvelteKit(input: ErrorPageInput) {
  return {
    path: "src/routes/+error.svelte",
    content: `<script>
  /**
   * Error page for ${input.projectName}.
   * Auto-generated by ShipReady. Handles both 404 and 500 errors.
   */
  import { page } from "$app/stores";
</script>

<svelte:head>
  <title>{$page.status === 404 ? "404 — ${input.projectName}" : "Error — ${input.projectName}"}</title>
</svelte:head>

<main class="error-page">
  <p class="error-code">{$page.status === 404 ? "404" : "500"}</p>
  <h1>
    {$page.status === 404 ? "Page not found" : "Something went wrong"}
  </h1>
  <p class="error-message">
    {$page.status === 404
      ? "The page you're looking for doesn't exist or has been moved."
      : "We hit an unexpected error. Try again, or come back in a few minutes."}
  </p>
  <a href="/" class="button">Back to home</a>
</main>

<style>
  .error-page {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 1.5rem;
    font-family: system-ui, -apple-system, sans-serif;
    background: #0a0a09;
    color: #fafaf9;
    text-align: center;
  }
  .error-code {
    font-family: monospace;
    font-size: 0.875rem;
    color: #a8a29e;
    margin-bottom: 1rem;
  }
  h1 {
    font-size: 2.25rem;
    font-weight: 600;
    margin-bottom: 1rem;
  }
  .error-message {
    color: #a8a29e;
    margin-bottom: 2rem;
    line-height: 1.6;
    max-width: 28rem;
  }
  .button {
    display: inline-block;
    padding: 0.5rem 1rem;
    background: #c4f542;
    color: #0a0a09;
    border-radius: 0.5rem;
    font-weight: 500;
    text-decoration: none;
  }
</style>
`,
  };
}

function generateNotFoundStatic(input: ErrorPageInput) {
  return {
    path: "public/404.html",
    content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>404 — ${input.projectName}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 1.5rem;
      font-family: system-ui, -apple-system, sans-serif;
      background: #0a0a09;
      color: #fafaf9;
    }
    .container { max-width: 28rem; text-align: center; }
    .code { font-family: monospace; font-size: 0.875rem; color: #a8a29e; margin-bottom: 1rem; }
    h1 { font-size: 2.25rem; font-weight: 600; margin-bottom: 1rem; }
    p { color: #a8a29e; margin-bottom: 2rem; line-height: 1.6; }
    .button {
      display: inline-block;
      padding: 0.5rem 1rem;
      background: #c4f542;
      color: #0a0a09;
      border-radius: 0.5rem;
      font-weight: 500;
      text-decoration: none;
    }
  </style>
</head>
<body>
  <div class="container">
    <p class="code">404</p>
    <h1>Page not found</h1>
    <p>The page you're looking for doesn't exist or has been moved.</p>
    <a href="/" class="button">Back to home</a>
  </div>
</body>
</html>
`,
  };
}

// ─────────────────────────────────────────────────────────────
//  Error boundary / 500 page
// ─────────────────────────────────────────────────────────────

export function generateErrorPage(input: ErrorPageInput): { path: string; content: string } | null {
  if (hasAppRouter(input.framework)) {
    return generateErrorPageNextjs(input);
  }
  if (isAstro(input.framework)) {
    return generateErrorPageAstro(input);
  }
  // SvelteKit uses the same +error.svelte for both 404 and 500.
  // If it was already generated by generateNotFound, skip.
  // generateNotFound already handles this, so we skip here.
  // The dedup happens in index.ts.
  if (isSvelteKit(input.framework)) {
    return null;
  }
  // Vite / unknown — static HTML
  return generateErrorPageStatic(input);
}

function generateErrorPageNextjs(input: ErrorPageInput) {
  return {
    path: "app/error.tsx",
    content: `"use client";

import { useEffect } from "react";
import Link from "next/link";

/**
 * Error boundary for ${input.projectName}.
 * Auto-generated by ShipReady. This catches unhandled exceptions in any
 * route segment. Customize the message, then make sure you're reporting
 * errors to Sentry / PostHog / your own logger.
 */
export default function Error({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  useEffect(() => {
    // TODO: send to your error reporting service
    console.error(error);
  }, [error]);

  return (
    <main className="min-h-screen flex items-center justify-center px-6">
      <div className="max-w-md text-center">
        <p className="font-mono text-sm text-foreground-dim mb-4">500</p>
        <h1 className="font-display text-5xl tracking-tight mb-4">
          Something went wrong
        </h1>
        <p className="text-foreground-muted mb-8 leading-relaxed">
          We hit an unexpected error. The team has been notified. Try again,
          or come back in a few minutes.
        </p>
        {error.digest && (
          <p className="font-mono text-xs text-foreground-dim mb-4">
            ref: {error.digest}
          </p>
        )}
        <div className="flex gap-3 justify-center">
          <button
            onClick={reset}
            className="px-4 py-2 rounded-lg bg-accent text-accent-foreground font-medium hover:brightness-110 transition-all"
          >
            Try again
          </button>
          <Link
            href="/"
            className="px-4 py-2 rounded-lg border border-border hover:bg-background-elevated transition-all"
          >
            Back to home
          </Link>
        </div>
      </div>
    </main>
  );
}
`,
  };
}

function generateErrorPageAstro(input: ErrorPageInput) {
  return {
    path: "src/pages/500.astro",
    content: `---
/**
 * Custom 500 error page for ${input.projectName}.
 * Auto-generated by ShipReady.
 */
const siteUrl = "${input.siteUrl || `https://${input.projectName.toLowerCase()}.com`}";
---

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Error — ${input.projectName}</title>
    <link rel="canonical" href=\`\${siteUrl}/500\` />
  </head>
  <body>
    <main style="
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 1.5rem;
      font-family: system-ui, -apple-system, sans-serif;
      background: #0a0a09;
      color: #fafaf9;
    ">
      <div style="max-width: 28rem; text-align: center;">
        <p style="font-family: monospace; font-size: 0.875rem; color: #a8a29e; margin-bottom: 1rem;">500</p>
        <h1 style="font-size: 2.25rem; font-weight: 600; margin-bottom: 1rem;">Something went wrong</h1>
        <p style="color: #a8a29e; margin-bottom: 2rem; line-height: 1.6;">
          We hit an unexpected error. Try again, or come back in a few minutes.
        </p>
        <a href="/" style="
          display: inline-block;
          padding: 0.5rem 1rem;
          background: #c4f542;
          color: #0a0a09;
          border-radius: 0.5rem;
          font-weight: 500;
          text-decoration: none;
        ">
          Try again
        </a>
      </div>
    </main>
  </body>
</html>
`,
  };
}

function generateErrorPageStatic(input: ErrorPageInput) {
  return {
    path: "public/500.html",
    content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>Error — ${input.projectName}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 1.5rem;
      font-family: system-ui, -apple-system, sans-serif;
      background: #0a0a09;
      color: #fafaf9;
    }
    .container { max-width: 28rem; text-align: center; }
    .code { font-family: monospace; font-size: 0.875rem; color: #a8a29e; margin-bottom: 1rem; }
    h1 { font-size: 2.25rem; font-weight: 600; margin-bottom: 1rem; }
    p { color: #a8a29e; margin-bottom: 2rem; line-height: 1.6; }
    .button {
      display: inline-block;
      padding: 0.5rem 1rem;
      background: #c4f542;
      color: #0a0a09;
      border-radius: 0.5rem;
      font-weight: 500;
      text-decoration: none;
    }
  </style>
</head>
<body>
  <div class="container">
    <p class="code">500</p>
    <h1>Something went wrong</h1>
    <p>We hit an unexpected error. Try again, or come back in a few minutes.</p>
    <a href="/" class="button">Try again</a>
  </div>
</body>
</html>
`,
  };
}

// ─────────────────────────────────────────────────────────────
//  Global error (Next.js only — no equivalent elsewhere)
// ─────────────────────────────────────────────────────────────

export function generateGlobalError(input: ErrorPageInput): { path: string; content: string } | null {
  if (input.framework !== "nextjs") {
    // Global error is a Next.js-specific concept. Remix handles this
    // differently, and no other framework has an equivalent.
    return null;
  }

  return {
    path: "app/global-error.tsx",
    content: `"use client";

/**
 * Global error boundary for ${input.projectName}.
 * Auto-generated by ShipReady. This is the LAST line of defense — it
 * catches errors that happen in the root layout itself, where error.tsx
 * can't reach. Must include its own <html> and <body> tags.
 *
 * Docs: https://nextjs.org/docs/app/api-reference/file-conventions/error#global-error
 */
export default function GlobalError({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  return (
    <html lang="en">
      <body
        style={{
          minHeight: "100vh",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          padding: "1.5rem",
          background: "#0a0a09",
          color: "#fafaf9",
          fontFamily: "system-ui, -apple-system, sans-serif",
        }}
      >
        <div style={{ maxWidth: "28rem", textAlign: "center" }}>
          <p
            style={{
              fontFamily: "monospace",
              fontSize: "0.875rem",
              color: "#a8a29e",
              marginBottom: "1rem",
            }}
          >
            Critical error
          </p>
          <h1
            style={{
              fontSize: "2.25rem",
              fontWeight: 600,
              marginBottom: "1rem",
            }}
          >
            Something broke
          </h1>
          <p
            style={{
              color: "#a8a29e",
              marginBottom: "2rem",
              lineHeight: 1.6,
            }}
          >
            The site hit an unrecoverable error. Try refreshing the page.
            If it keeps happening, contact support.
          </p>
          {error.digest && (
            <p
              style={{
                fontFamily: "monospace",
                fontSize: "0.75rem",
                color: "#78716c",
                marginBottom: "1rem",
              }}
            >
              ref: {error.digest}
            </p>
          )}
          <button
            onClick={reset}
            style={{
              padding: "0.5rem 1rem",
              background: "#c4f542",
              color: "#0a0a09",
              border: "none",
              borderRadius: "0.5rem",
              fontWeight: 500,
              cursor: "pointer",
            }}
          >
            Try again
          </button>
        </div>
      </body>
    </html>
  );
}
`,
  };
}
