/**
 * .gitignore additions generator.
 *
 * Returns a Fix that APPENDS lines to .gitignore. The user has to
 * merge it manually (auto-merge is too risky — we'd corrupt their
 * existing .gitignore).
 */

export interface GitignoreAdditionsInput {
  /** What entries to add */
  missing: string[];
}

export function generateGitignoreAdditions(
  input: GitignoreAdditionsInput
): { path: string; content: string } {
  const header = `# Lines to append to your .gitignore
# Auto-generated by ShipReady.

`;
  return {
    path: ".gitignore.additions",
    content: header + input.missing.join("\n") + "\n",
  };
}
