/**
 * .gitignore additions generator.
 *
 * Returns a Fix that APPENDS lines to .gitignore. The user has to
 * merge it manually (auto-merge is too risky — we'd corrupt their
 * existing .gitignore).
 */

import type { ProjectContext } from "../types";
import type { Fix } from "../types";

export interface GitignoreAdditionsInput {
  /** What entries we'd like to add (may be filtered) */
  requested: string[];
  /** Existing .gitignore content (if any) to avoid duplicates */
  existingContent?: string;
}

export function generateGitignoreAdditions(
  input: GitignoreAdditionsInput
): Fix {
  // Parse existing content into a Set of lines (trimmed, non-empty, not comments)
  const existingLines = new Set<string>();
  if (input.existingContent) {
    for (const line of input.existingContent.split("\n")) {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith("#")) {
        existingLines.add(trimmed);
      }
    }
  }

  // Filter out entries that already exist
  const toAdd = input.requested.filter((entry) => !existingLines.has(entry));

  if (toAdd.length === 0) {
    // Nothing to add — return an empty fix (will be filtered out later)
    return {
      path: ".gitignore.additions",
      content: "",
      description: "No new .gitignore entries needed",
      issueId: "incomplete-gitignore",
      isNew: false,
    };
  }

  const header = `# Lines to append to your .gitignore
# Auto-generated by ShipReady.

`;
  return {
    path: ".gitignore.additions",
    content: header + toAdd.join("\n") + "\n",
    description: `.gitignore additions — append these to your existing .gitignore`,
    issueId: "incomplete-gitignore",
    isNew: true,
  };
}