/**
 * JSON-LD structured data generator.
 *
 * Generates an Organization schema as a default. This is the simplest
 * useful JSON-LD — it tells Google "this is a business called X, with
 * logo Y, social profiles Z, contact email A." It triggers the
 * knowledge panel and brand search enhancements.
 *
 * For e-commerce, blog, and SaaS-specific schemas, the user can extend
 * this with Product, Article, SoftwareApplication, etc.
 */

import type { Framework } from "../framework";
import type { CodebaseContext } from "../types";
import { generateJsonLdSchemaWithAI } from "./_ai-prompts";
import { aiEnabled } from "@/lib/ai";

export interface JsonLdInput {
  framework: Framework;
  projectName: string;
  /** Short description – if omitted we try to infer from README via AI */
  description?: string;
  siteUrl: string;
  logoUrl?: string;
  /** Social profile URLs */
  sameAs?: string[];
  contactEmail?: string;
  /** Optional: AI-curated codebase context for richer schema */
  codebase?: CodebaseContext;
}

export async function generateJsonLd(input: JsonLdInput): Promise<{ path: string; content: string }> {
  const url = input.siteUrl.replace(/\/$/, "");
  const logo = input.logoUrl || `${url}/logo.png`;
  const email = input.contactEmail || "";

  // AI path – try to build a more detailed schema from README/codebase
  if (input.codebase && aiEnabled) {
    const aiResult = await generateJsonLdSchemaWithAI({
      projectName: input.projectName,
      description: input.codebase.description || input.description || `${input.projectName} — a modern web app.`,
      siteUrl: input.siteUrl,
      readmeSnippet: input.codebase.existingCopy.readmeSnippet,
      contactEmail: input.contactEmail,
    });
    if (aiResult.ok) {
      const schema = aiResult.schema;
      const jsonString = JSON.stringify(schema, null, 2);
      if (input.framework === "nextjs" || input.framework === "remix") {
        return {
          path: "app/jsonld.tsx",
          content: `/**
 * JSON-LD Organization schema for ${input.projectName}.
 * Auto-generated by ShipReady. Render this in your app/layout.tsx:
 *
 *   import { JsonLd } from "./jsonld";
 *
 *   export default function RootLayout({ children }) {
 *     return (
 *       <html>
 *         <body>
 *           <JsonLd />
 *           {children}
 *         </body>
 *       </html>
 *     );
 *   }
 */
export function JsonLd() {
  const data = ${jsonString};
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}
`,
        };
      }
      // Static fallback – emit a script tag
      return {
        path: "public/jsonld.html",
        content: `<!-- JSON-LD Organization schema for ${input.projectName} -->
<!-- Auto-generated by ShipReady. Paste this into your <head>. -->

<script type="application/ld+json">
${jsonString}
</script>
`,
      };
    }
  }

  // Fallback – static schema if AI not available or fails
  const json = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: input.projectName,
    url,
    logo,
    description: input.description || `${input.projectName} — a modern web app.`,
    ...(email ? { email } : {}),
    ...(input.sameAs && input.sameAs.length > 0 ? { sameAs: input.sameAs } : {}),
  };

  const jsonString = JSON.stringify(json, null, 2);

  if (input.framework === "nextjs" || input.framework === "remix") {
    // Generate a TypeScript component the user can drop into their root layout
    return {
      path: "app/jsonld.tsx",
      content: `/**
 * JSON-LD Organization schema for ${input.projectName}.
 * Auto-generated by ShipReady. Render this in your app/layout.tsx:
 *
 *   import { JsonLd } from "./jsonld";
 *
 *   export default function RootLayout({ children }) {
 *     return (
 *       <html>
 *         <body>
 *           <JsonLd />
 *           {children}
 *         </body>
 *       </html>
 *     );
 *   }
 */
export function JsonLd() {
  const data = ${jsonString};
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}
`,
    };
  }

  // Static HTML — emit a <script> snippet
  return {
    path: "public/jsonld.html",
    content: `<!-- JSON-LD Organization schema for ${input.projectName} -->
<!-- Auto-generated by ShipReady. Paste this into your <head>. -->

<script type="application/ld+json">
${jsonString}
</script>
`,
  };
}
