/**
 * Web app manifest generator.
 *
 * For Next.js / Remix, generates app/manifest.ts using the typed
 * MetadataRoute.Manifest export. For other frameworks, generates a
 * static manifest.json.
 */

import type { Framework } from "../framework";
import type { CodebaseContext } from "../types";

export interface ManifestInput {
  framework: Framework;
  projectName: string;
  description: string;
  /** Optional: AI-curated codebase context for brand color */
  codebase?: CodebaseContext;
  themeColor?: string;
  backgroundColor?: string;
}

const DEFAULT_THEME = "#0a0a09";
const DEFAULT_BG = "#0a0a09";

export function generateManifest(input: ManifestInput): { path: string; content: string } {
  // Use brand color from codebase if available, otherwise fallback
  const theme = input.themeColor || input.codebase?.brandColor || DEFAULT_THEME;
  const bg = input.backgroundColor || DEFAULT_BG;

  if (input.framework === "nextjs" || input.framework === "remix") {
    return {
      path: "app/manifest.ts",
      content: `import type { MetadataRoute } from "next";

/**
 * Web app manifest for ${input.projectName}.
 * Auto-generated by ShipReady. This makes your site installable as a PWA.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "${input.projectName}",
    short_name: "${input.projectName}",
    description: "${(input.description || input.codebase?.description || `${input.projectName} — a modern web app.`).replace(/"/g, '\\"')}",
    start_url: "/",
    display: "standalone",
    background_color: "${bg}",
    theme_color: "${theme}",
    icons: [
      {
        src: "/favicon.ico",
        sizes: "any",
        type: "image/x-icon",
      },
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
      },
      {
        src: "/apple-icon.png",
        sizes: "180x180",
        type: "image/png",
      },
    ],
  };
}
`,
    };
  }

  return {
    path: "public/manifest.json",
    content: JSON.stringify(
      {
        name: input.projectName,
        short_name: input.projectName,
        description: input.description,
        start_url: "/",
        display: "standalone",
        background_color: bg,
        theme_color: theme,
        icons: [
          { src: "/favicon.ico", sizes: "any", type: "image/x-icon" },
          { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
          { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
        ],
      },
      null,
      2
    ) + "\n",
  };
}
