/**
 * Open Graph / meta tags generator.
 *
 * Generates a Metadata export for Next.js / Remix, or an HTML <head>
 * snippet for static frameworks. The output is meant to be COPIED into
 * the user's existing layout — we don't auto-merge.
 */

import type { Framework } from "../framework";
import { frameworkPaths } from "../framework";

export interface OgTagsInput {
  framework: Framework;
  projectName: string;
  description: string;
  siteUrl: string;
  /** Optional Twitter handle */
  twitterHandle?: string;
}

export function generateOgTags(input: OgTagsInput): { path: string; content: string } {
  const paths = frameworkPaths(input.framework);
  const desc = input.description.replace(/"/g, '\\"');
  const url = input.siteUrl.replace(/\/$/, "");

  // Next.js / Remix — generate `app/layout.metadata.ts` for the user to import
  if (input.framework === "nextjs" || input.framework === "remix") {
    return {
      path: "app/metadata.ts",
      content: `import type { Metadata } from "next";

/**
 * Default metadata for ${input.projectName}.
 * Auto-generated by ShipReady. Import this in your app/layout.tsx:
 *
 *   import { metadata } from "./metadata";
 *   export const metadata = metadata;
 */
export const metadata: Metadata = {
  title: {
    default: "${input.projectName}",
    template: \`%s · \${"${input.projectName}"}\`,
  },
  description: "${desc}",
  metadataBase: new URL("${url}"),
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "${url}",
    siteName: "${input.projectName}",
    title: "${input.projectName}",
    description: "${desc}",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "${input.projectName}",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "${input.projectName}",
    description: "${desc}",
    images: ["/opengraph-image"],
    ${input.twitterHandle ? `creator: "${input.twitterHandle}",` : ""}
  },
  alternates: {
    canonical: "${url}",
  },
};
`,
    };
  }

  // Static HTML — generate an <head> snippet
  return {
    path: "public/meta-tags.html",
    content: `<!-- Open Graph and meta tags for ${input.projectName} -->
<!-- Auto-generated by ShipReady. Paste this into your <head>. -->

<title>${input.projectName}</title>
<meta name="description" content="${desc}" />

<!-- Open Graph -->
<meta property="og:type" content="website" />
<meta property="og:url" content="${url}" />
<meta property="og:title" content="${input.projectName}" />
<meta property="og:description" content="${desc}" />
<meta property="og:image" content="${url}/og-image.png" />
<meta property="og:site_name" content="${input.projectName}" />

<!-- Twitter -->
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${input.projectName}" />
<meta name="twitter:description" content="${desc}" />
<meta name="twitter:image" content="${url}/og-image.png" />
${input.twitterHandle ? `<meta name="twitter:creator" content="${input.twitterHandle}" />` : ""}

<!-- Canonical -->
<link rel="canonical" href="${url}" />
`,
  };
}
