/**
 * Open Graph / meta tags generator.
 *
 * Generates a Metadata export for Next.js / Remix, or an HTML <head>
 * snippet for static frameworks. The output is meant to be COPIED into
 * the user's existing layout — we don't auto-merge.
 */

import type { Framework } from "../framework";
import { frameworkPaths } from "../framework";
import { generateOgDescriptionWithAI } from "./_ai-prompts";
import { aiEnabled } from "@/lib/ai";
import type { CodebaseContext } from "../types";

export interface OgTagsInput {
  framework: Framework;
  projectName: string;
  /** Description of the project. If not provided and no AI, a fallback is used. */
  description?: string;
  siteUrl: string;
  /** Optional: Twitter handle to include in meta tags */
  twitterHandle?: string;
  /** Optional: AI-curated codebase context for description extraction and Twitter handle inference */
  codebase?: CodebaseContext;
}

export async function generateOgTags(input: OgTagsInput): Promise<{ path: string; content: string }> {
  // Infer or generate the best description
  let description = input.description || "";

  // AI path: try to extract a punchier description from README
  if (input.codebase && aiEnabled && (!description || description.length < 20)) {
    const aiResult = await generateOgDescriptionWithAI({
      projectName: input.projectName,
      description: input.codebase.description || description || `${input.projectName} — a modern web app.`,
      readmeSnippet: input.codebase.existingCopy.readmeSnippet,
    });
    if (aiResult.ok) {
      description = aiResult.text;
    }
  }

  // Fallback if no AI or AI failed
  if (!description || description.length < 10) {
    description = `${input.projectName} — a modern web app built with care.`;
  }

  // Infer twitterHandle from codebase if not provided
  let twitterHandle = input.twitterHandle || "";
  if (!twitterHandle && input.codebase?.existingCopy.readmeSnippet) {
    const match = input.codebase.existingCopy.readmeSnippet.match(/twitter\.com\/(\/\w+)|@(\w+)/i);
    if (match) {
      twitterHandle = match[1] || match[2] || "";
    }
  }

  const paths = frameworkPaths(input.framework);
  const desc = description.replace(/"/g, '\\"');
  const url = input.siteUrl.replace(/\/$/, "");

  // Next.js / Remix — generate `app/layout.metadata.ts` for the user to import
  if (input.framework === "nextjs" || input.framework === "remix") {
    return {
      path: "app/metadata.ts",
      content: `import type { Metadata } from "next";

/**
 * Default metadata for ${input.projectName}.
 * Auto-generated by ShipReady. Import this in your app/layout.tsx:
 *
 *   import { metadata } from "./metadata";
 *   export const metadata = metadata;
 */
export const metadata: Metadata = {
  title: {
    default: "${input.projectName}",
    template: \`%s · \${"${input.projectName}"}\`,
  },
  description: "${desc}",
  metadataBase: new URL("${url}"),
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "${url}",
    siteName: "${input.projectName}",
    title: "${input.projectName}",
    description: "${desc}",
    images: [
      {
        url: "/opengraph-image",
        width: 1200,
        height: 630,
        alt: "${input.projectName}",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "${input.projectName}",
    description: "${desc}",
    images: ["/opengraph-image"],
    ${twitterHandle ? `creator: "${twitterHandle}",` : ""}
  },
  alternates: {
    canonical: "${url}",
  },
};
`,
    };
  }

  // Static HTML — generate an <head> snippet
  return {
    path: "public/meta-tags.html",
    content: `<!-- Open Graph and meta tags for ${input.projectName} -->
<!-- Auto-generated by ShipReady. Paste this into your <head>. -->

<title>${input.projectName}</title>
<meta name="description" content="${desc}" />

<!-- Open Graph -->
<meta property="og:type" content="website" />
<meta property="og:url" content="${url}" />
<meta property="og:title" content="${input.projectName}" />
<meta property="og:description" content="${desc}" />
<meta property="og:image" content="${url}/og-image.png" />
<meta property="og:site_name" content="${input.projectName}" />

<!-- Twitter -->
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${input.projectName}" />
<meta name="twitter:description" content="${desc}" />
<meta name="twitter:image" content="${url}/og-image.png" />
${twitterHandle ? `<meta name="twitter:creator" content="${twitterHandle}" />` : ""}

<!-- Canonical -->
<link rel="canonical" href="${url}" />
`,
  };
}
