/**
 * Privacy policy generator.
 *
 * Produces a context-aware privacy policy in Markdown.
 * The content is driven by the user's ProjectContext — the 5 answers
 * determine which sections are included, what frameworks are referenced,
 * and what disclosures are made.
 *
 * The text is a heavily-adapted version of a CC0 template, modified to:
 *   - Skip irrelevant sections (e.g. payment processor if no payments)
 *   - Use correct legal framework names based on region
 *   - Use business-type appropriate language
 *   - Include "not legal advice" disclaimer
 *
 * This is NOT a substitute for legal review. For high-risk businesses
 * (healthcare, finance, kids' products), always pay a lawyer.
 */

import type { ProjectContext, PolicyRules } from "../context";
import { deriveRules } from "../context";

export interface PrivacyPolicyInput {
  context: ProjectContext;
  /** Company / project name (we'll infer from package.json or repo name if not provided) */
  projectName: string;
  /** Contact email (e.g. privacy@yourdomain.com) */
  contactEmail: string;
  /** Effective date — defaults to "today" */
  effectiveDate?: string;
  /** Where the data is hosted (e.g. "United States", "EU") */
  dataHosting?: string;
}

export function generatePrivacyPolicy(input: PrivacyPolicyInput): string {
  const ctx = input.context;
  const rules = deriveRules(ctx);
  const date = input.effectiveDate || new Date().toISOString().slice(0, 10);
  const hosting = input.dataHosting || (ctx.region === "eu" ? "European Union" : "United States");

  const sections: string[] = [];

  // Header
  sections.push(`# Privacy Policy

_Last updated: ${date}_

**${input.projectName}** ("we", "our", "us") operates the website and service located at the domain provided above (the "Service"). This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit or use the Service.

If you have any questions about this Privacy Policy, please contact us at **${input.contactEmail}**.

> **Disclaimer**: This Privacy Policy is generated by ShipReady based on the information you provided. It is intended as a starting point and is **not legal advice**. We recommend having a qualified attorney review it before going to production, especially if you operate in regulated industries (healthcare, finance, children's products) or handle sensitive personal data.
`);

  // 1. Information We Collect
  sections.push(generateDataCollectionSection(ctx));

  // 2. How We Use Your Information
  sections.push(generateUseSection(ctx));

  // 3. Legal Basis (GDPR)
  if (rules.dataSubjectRights) {
    sections.push(generateLegalBasisSection());
  }

  // 4. Cookies and Tracking
  if (ctx.usesCookies) {
    sections.push(generateCookiesSection());
  }

  // 5. Third-Party Services
  sections.push(generateThirdPartySection(ctx, hosting));

  // 6. International Data Transfers
  if (rules.internationalTransfers) {
    sections.push(generateInternationalTransfersSection(hosting));
  }

  // 7. Data Retention
  sections.push(generateRetentionSection(ctx));

  // 8. Your Rights
  if (rules.dataSubjectRights) {
    sections.push(generateGdprRightsSection(input.contactEmail));
  } else if (rules.doNotSell) {
    sections.push(generateCcpaRightsSection(input.contactEmail));
  }

  // 9. Children's Privacy
  sections.push(generateChildrensSection());

  // 10. Security
  sections.push(generateSecuritySection());

  // 11. Changes to This Policy
  sections.push(generateChangesSection());

  // 12. Contact
  sections.push(generateContactSection(input.contactEmail));

  // Footer — frameworks
  sections.push(`---

_This Privacy Policy is governed by: ${rules.frameworks.join(", ") || "applicable local privacy laws"}._

_Generated by [ShipReady](https://shipready.dev) · This is a template, not legal advice._`);

  return sections.join("\n\n---\n\n");
}

function generateDataCollectionSection(ctx: ProjectContext): string {
  const items: string[] = [];

  items.push(`We may collect the following categories of information:`);

  if (ctx.businessType === "saas") {
    items.push(`
- **Account information**: When you sign up, we collect your email address, name (if provided), and password (stored as a one-way hash, never in plain text).
- **Usage data**: We collect information about how you interact with the Service, including features used, pages visited, and actions taken.
- **Device and connection data**: We automatically log your IP address, browser type, operating system, and referring URL.`);
  } else if (ctx.businessType === "ecommerce") {
    items.push(`
- **Account information**: Email, name, shipping/billing address when you create an account or place an order.
- **Order information**: Products purchased, transaction amounts, order history.
- **Payment information**: Payment card details are processed by our payment processor and are never stored on our servers.
- **Device and connection data**: IP address, browser type, and referring URL.`);
  } else if (ctx.businessType === "blog") {
    items.push(`
- **Comments and submissions**: If you leave a comment, we collect your name (if provided), email (never displayed publicly), and the comment content.
- **Newsletter subscription**: If you subscribe, we collect your email address.
- **Analytics**: We collect anonymized page view statistics.`);
  } else {
    items.push(`
- **Information you provide**: Information you submit through forms, account creation, or direct communication.
- **Automatic data**: IP address, browser type, operating system, and pages visited.`);
  }

  if (ctx.usesCookies) {
    items.push(`- **Cookies and similar tracking**: See the Cookies section below.`);
  }

  return `## 1. Information We Collect

${items.join("\n")}`;
}

function generateUseSection(ctx: ProjectContext): string {
  const uses: string[] = [];

  uses.push(`We use the information we collect for the following purposes:`);
  uses.push(`
- To provide, operate, and maintain the Service
- To improve, personalize, and expand the Service
- To communicate with you, including responding to inquiries and sending service-related announcements`);

  if (ctx.collectsEmails) {
    uses.push(`- To send you newsletters, marketing communications, and product updates (you can opt out at any time via the unsubscribe link in any email)`);
  }

  if (ctx.processesPayments) {
    uses.push(`- To process transactions and manage your account`);
  }

  if (ctx.usesCookies) {
    uses.push(`- To analyze usage patterns and improve the Service`);
  }

  uses.push(`- To detect and prevent fraud or abuse
- To comply with legal obligations`);

  return `## 2. How We Use Your Information

${uses.join("\n")}`;
}

function generateLegalBasisSection(): string {
  return `## 3. Legal Basis for Processing (GDPR)

If you are located in the European Economic Area (EEA) or the United Kingdom, our legal basis for collecting and using your personal data depends on the type of information and the context in which we collect it.

We will normally rely on one of the following legal bases:

- **Performance of a contract**: When you sign up for or use the Service, processing your data is necessary to perform the contract we have with you.
- **Legitimate interests**: We may process your data where it is in our legitimate interests to do so (for example, to improve our Service or for security purposes), and these interests are not overridden by your rights.
- **Consent**: We rely on your consent for specific, clearly disclosed purposes (such as marketing emails or non-essential cookies). You have the right to withdraw consent at any time.
- **Legal obligation**: In some cases, we may be legally required to process your data (for example, to comply with tax laws).`;
}

function generateCookiesSection(): string {
  return `## 4. Cookies and Tracking Technologies

We use cookies and similar tracking technologies to operate and analyze the Service.

**Types of cookies we use:**

- **Strictly necessary cookies**: Required for the Service to function (e.g., authentication, security). These cannot be disabled.
- **Analytics cookies**: Help us understand how visitors use the Service so we can improve it. We use these to count visits and traffic sources.
- **Functionality cookies**: Remember choices you've made (e.g., language, region).

**Managing cookies:**

Most browsers allow you to refuse cookies or delete existing ones. Note that disabling certain cookies may impact the functionality of the Service.

For European users, we will request your consent before setting non-essential cookies. You may withdraw consent at any time.`;
}

function generateThirdPartySection(ctx: ProjectContext, _hosting: string): string {
  const services: string[] = [];

  if (ctx.processesPayments) {
    services.push(`- **Payment processor**: We use a third-party payment processor (such as [Stripe](https://stripe.com/privacy)) to handle transactions. Your payment information is sent directly to the processor and is governed by their privacy policy.`);
  }

  if (ctx.usesCookies) {
    services.push(`- **Analytics provider**: We use analytics services to understand how the Service is used. These may set cookies or read identifiers from your device.`);
  }

  services.push(`- **Hosting provider**: Our Service is hosted on infrastructure provided by trusted third-party providers. These providers have access to data only as necessary to provide hosting services.`);
  services.push(`- **Email service**: We use a third-party email service to send transactional and (if applicable) marketing emails.`);

  return `## 5. Third-Party Services

We rely on the following categories of third-party services to operate the Service. Each of these services has its own privacy practices:

${services.join("\n")}

We require these third parties to use your personal data only as necessary to provide their services to us.`;
}

function generateInternationalTransfersSection(hosting: string): string {
  return `## 6. International Data Transfers

Your information may be transferred to and processed in countries other than your country of residence, including the **${hosting}**.

When we transfer your personal data outside the European Economic Area, the United Kingdom, or Switzerland, we rely on appropriate safeguards such as:

- **Standard Contractual Clauses (SCCs)** approved by the European Commission
- **Adequacy decisions** for transfers to countries deemed to provide adequate protection
- **Your explicit consent**, where appropriate

If you would like more information about the specific safeguards used, please contact us.`;
}

function generateRetentionSection(ctx: ProjectContext): string {
  let retention = `We will retain your personal data only for as long as necessary to fulfill the purposes outlined in this Privacy Policy, unless a longer retention period is required or permitted by law (such as tax, accounting, or legal requirements).`;

  if (ctx.collectsEmails) {
    retention += `\n\nIf you have an account with us, we will retain your account data for as long as your account is active. You may request deletion of your account at any time.`;
  }

  if (ctx.usesCookies) {
    retention += `\n\nAnalytics data is retained for a maximum of 26 months in aggregate form.`;
  }

  return `## 7. Data Retention

${retention}`;
}

function generateGdprRightsSection(email: string): string {
  return `## 8. Your Rights (GDPR / UK GDPR)

If you are located in the EEA or the UK, you have the following rights with respect to your personal data:

- **Right of access** (Art. 15): Request a copy of the personal data we hold about you
- **Right to rectification** (Art. 16): Correct inaccurate or incomplete data
- **Right to erasure** (Art. 17): Request deletion of your data ("right to be forgotten")
- **Right to restrict processing** (Art. 18): Ask us to limit how we process your data
- **Right to data portability** (Art. 20): Receive your data in a machine-readable format
- **Right to object** (Art. 21): Object to processing based on legitimate interests or for direct marketing
- **Right to withdraw consent** (Art. 7(3)): Where we rely on consent, withdraw it at any time
- **Right to lodge a complaint** (Art. 77): File a complaint with your local data protection authority

To exercise any of these rights, please contact us at **${email}**. We will respond within 30 days.`;
}

function generateCcpaRightsSection(email: string): string {
  return `## 8. Your Rights (CCPA)

If you are a California resident, you have the following rights:

- **Right to know** what personal information we collect, use, share, or sell
- **Right to delete** personal information we have collected from you
- **Right to opt-out** of the sale of your personal information
- **Right to non-discrimination** for exercising your CCPA rights

To exercise these rights, please contact us at **${email}**.`;
}

function generateChildrensSection(): string {
  return `## 9. Children's Privacy

The Service is not directed to children under the age of 13 (or under 16 in the EEA/UK). We do not knowingly collect personal data from children.

If you believe we have collected information from a child, please contact us and we will take steps to delete the information promptly.`;
}

function generateSecuritySection(): string {
  return `## 10. Security

We implement appropriate technical and organizational safeguards to protect your personal data against unauthorized access, alteration, disclosure, or destruction. These measures include encryption in transit (HTTPS/TLS), access controls, and regular security reviews.

However, no method of transmission over the Internet or electronic storage is 100% secure. We cannot guarantee absolute security.`;
}

function generateChangesSection(): string {
  return `## 11. Changes to This Privacy Policy

We may update this Privacy Policy from time to time. When we do, we will revise the "Last updated" date at the top of this policy.

If the changes are material, we will provide more prominent notice (such as a banner on the Service or an email notification). Your continued use of the Service after the effective date constitutes your acceptance of the updated policy.`;
}

function generateContactSection(email: string): string {
  return `## 12. Contact Us

If you have any questions about this Privacy Policy or our data practices, please contact us at:

**Email**: ${email}

We will respond to your inquiry as soon as possible, and within any timeframes required by applicable law.`;
}
