/**
 * robots.txt generator.
 *
 * Generates a basic robots.txt that:
 *   - Allows all crawlers by default
 *   - Disallows /api/, /admin/, /_next/ (private routes)
 *   - Points to the sitemap
 *
 * For Next.js / Remix with metadata routes, this goes in `app/robots.ts`
 * (or `public/robots.txt` for non-Next). The Next.js variant returns
 * a config object; the static variant is a plain text file.
 */

import type { Framework } from "../framework";

export interface RobotsInput {
  framework: Framework;
  siteUrl: string;
  /**
   * Optional: real routes discovered from the codebase.
   * When provided, /api/ and /admin/ are only disallowed if they
   * actually exist in the project (prevents misleading robots.txt entries).
   */
  pages?: string[];
}

export function generateRobots(input: RobotsInput): { path: string; content: string } {
  const base = input.siteUrl.replace(/\/$/, "");
  const disallowed = buildDisallowedPaths(input.framework, input.pages);

  // Next.js / Remix — use the typed config approach
  if (input.framework === "nextjs" || input.framework === "remix") {
    return {
      path: "app/robots.ts",
      content: generateNextjsRobots(base, disallowed),
    };
  }

  // All other frameworks — static robots.txt in public/
  return {
    path: "public/robots.txt",
    content: generateStaticRobots(base, disallowed),
  };
}

/**
 * Build the list of paths to disallow based on the project's actual routes.
 * Only disallows /api/ and /admin/ when those routes actually exist.
 * Next.js internal path /_next/ is always disallowed for Next.js/Remix.
 */
function buildDisallowedPaths(framework: Framework, pages?: string[]): string[] {
  const disallowed: string[] = [];

  // Always disallow framework-internal paths
  if (framework === "nextjs" || framework === "remix") {
    disallowed.push("/_next/");
  }

  if (!pages) {
    // No route info available — use safest defaults
    disallowed.push("/api/", "/admin/");
    return disallowed;
  }

  // Only disallow paths that actually exist in the project.
  // Use regex to avoid false matches (e.g. "/apiary" shouldn't match "/api").
  const hasApiRoutes = pages.some((p) => /^\/api(\/|$)/.test(p));
  const hasAdminRoutes = pages.some((p) => /^\/admin(\/|$)/.test(p));

  if (hasApiRoutes) disallowed.push("/api/");
  if (hasAdminRoutes) disallowed.push("/admin/");

  return disallowed;
}

function generateNextjsRobots(base: string, disallowed: string[]): string {
  const disallowStr = disallowed.map((d) => `"${d}"`).join(", ");

  return `import type { MetadataRoute } from "next";

/**
 * robots.txt for this site.
 * Auto-generated by ShipReady.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: [${disallowStr}],
      },
    ],
    sitemap: \`${base}/sitemap.xml\`,
  };
}
`;
}

function generateStaticRobots(base: string, disallowed: string[]): string {
  const disallowLines = disallowed.map((d) => `Disallow: ${d}`).join("\n");

  return `# robots.txt for this site
# Auto-generated by ShipReady.

User-agent: *
Allow: /
${disallowLines}

Sitemap: ${base}/sitemap.xml
`;
}
