/**
 * robots.txt generator.
 *
 * Generates a basic robots.txt that:
 *   - Allows all crawlers by default
 *   - Disallows /api/, /admin/, /_next/ (private routes)
 *   - Points to the sitemap
 *
 * For Next.js / Remix with metadata routes, this goes in `app/robots.ts`
 * (or `public/robots.txt` for non-Next). The Next.js variant returns
 * a config object; the static variant is a plain text file.
 */

import type { Framework } from "../framework";
import { frameworkPaths } from "../framework";

export interface RobotsInput {
  framework: Framework;
  siteUrl: string;
}

export function generateRobots(input: RobotsInput): { path: string; content: string } {
  const base = input.siteUrl.replace(/\/$/, "");

  // Next.js / Remix — use the typed config approach
  if (input.framework === "nextjs" || input.framework === "remix") {
    return {
      path: "app/robots.ts",
      content: `import type { MetadataRoute } from "next";

/**
 * robots.txt for this site.
 * Auto-generated by ShipReady.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/", "/admin/", "/_next/"],
      },
    ],
    sitemap: \`${base}/sitemap.xml\`,
  };
}
`,
    };
  }

  // All other frameworks — static robots.txt in public/
  return {
    path: "public/robots.txt",
    content: `# robots.txt for this site
# Auto-generated by ShipReady.

User-agent: *
Allow: /
Disallow: /api/
Disallow: /admin/

Sitemap: ${base}/sitemap.xml
`,
  };
}
