/**
 * security.txt generator (RFC 9116).
 *
 * Creates the standard file at public/.well-known/security.txt that
 * tells security researchers how to contact you. The file uses a
 * 2-year expiry so it doesn't go stale.
 */

export interface SecurityTxtInput {
  projectName: string;
  contactEmail: string;
  /** Optional URL to your security policy */
  policyUrl?: string;
  /** Optional URL to your bug bounty program */
  bountyUrl?: string;
}

export function generateSecurityTxt(input: SecurityTxtInput): { path: string; content: string } {
  // RFC 9116 requires ISO 8601 dates with the year 2 years in the future
  const expires = new Date();
  expires.setFullYear(expires.getFullYear() + 2);
  const expiresStr = expires.toISOString().replace(/T.*$/, "T00:00:00.000Z");

  const lines: string[] = [
    `# security.txt for ${input.projectName}`,
    `# Auto-generated by ShipReady. Re-generate every 2 years before expiry.`,
    `Contact: mailto:${input.contactEmail}`,
    `Expires: ${expiresStr}`,
    `Preferred-Languages: en`,
  ];

  if (input.policyUrl) {
    lines.push(`Policy: ${input.policyUrl}`);
  }
  if (input.bountyUrl) {
    lines.push(`Hiring: ${input.bountyUrl}`);
  }

  return {
    path: "public/.well-known/security.txt",
    content: lines.join("\n") + "\n",
  };
}
