/**
 * Security headers generator.
 *
 * Generates:
 *   - Next.js / Remix: next.config.headers.ts (typed, production-ready config)
 *   - All other frameworks: SECURITY-HEADERS.md (documentation with header
 *     values + copy-paste config snippets for common deployment platforms)
 *
 * Headers:
 *   - Content-Security-Policy: defense against XSS
 *   - Strict-Transport-Security: enforce HTTPS
 *   - X-Frame-Options: prevent clickjacking
 *   - X-Content-Type-Options: prevent MIME sniffing
 *   - Referrer-Policy: limit referrer leakage
 *   - Permissions-Policy: disable unused browser features
 */

import type { Framework } from "../framework";

export interface SecurityHeadersInput {
  framework: Framework;
  /** If true, the user is using Stripe — we allow js.stripe.com in CSP */
  usesPayments?: boolean;
  /** Project name used in the generated docs */
  projectName?: string;
}

export function generateSecurityHeaders(input: SecurityHeadersInput): { path: string; content: string } {
  const csp = buildCsp(input.usesPayments);

  if (input.framework === "nextjs" || input.framework === "remix") {
    return generateNextjsHeaders(input, csp);
  }

  return generateGenericHeaders(input, csp);
}

/**
 * Build a Content-Security-Policy string.
 * Allows Stripe domains when payments are enabled.
 */
function buildCsp(usesPayments?: boolean): string {
  const stripeScript = usesPayments ? " https://js.stripe.com" : "";
  const stripeFrame = usesPayments ? " https://js.stripe.com" : "";
  const stripeConnect = usesPayments ? " https://api.stripe.com" : "";
  return `default-src 'self'; script-src 'self' 'unsafe-inline'${stripeScript}; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'${stripeConnect}; frame-src 'self'${stripeFrame}`;
}

/**
 * Next.js / Remix — typed config file the user merges into next.config.ts.
 */
function generateNextjsHeaders(input: SecurityHeadersInput, csp: string) {
  const label = input.framework === "nextjs" ? "Next.js" : "Remix";
  return {
    path: "next.config.headers.ts",
    content: `import type { NextConfig } from "next";

/**
 * Security headers for ${label}.
 * Auto-generated by ShipReady. To use these, merge this headers() function
 * into your existing next.config.{ts,js,mjs}:
 *
 *   import { securityHeaders } from "./next.config.headers";
 *
 *   const nextConfig: NextConfig = {
 *     ...yourOtherConfig,
 *     async headers() {
 *       return [...yourOtherHeaders, ...securityHeaders()];
 *     },
 *   };
 */
export function securityHeaders() {
  return [
    {
      source: "/:path*",
      headers: [
        { key: "X-Frame-Options",         value: "DENY" },
        { key: "X-Content-Type-Options",  value: "nosniff" },
        { key: "Referrer-Policy",         value: "strict-origin-when-cross-origin" },
        { key: "Permissions-Policy",      value: "camera=(), microphone=(), geolocation=(), payment=()" },
        { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
        {
          key: "Content-Security-Policy",
          value: "${csp}",
        },
      ],
    },
  ];
}
`,
  };
}

/**
 * Generic documentation with header values and copy-paste configs
 * for every major deployment platform. No more wrong-format surprises.
 */
function generateGenericHeaders(input: SecurityHeadersInput, csp: string) {
  const hsts = "max-age=63072000; includeSubDomains; preload";
  const perms = "camera=(), microphone=(), geolocation=(), payment=()";

  return {
    path: "SECURITY-HEADERS.md",
    content: `# Security Headers for ${input.projectName || "your project"}

Auto-generated by ShipReady. These headers protect your site against XSS,
clickjacking, MIME sniffing, referrer leakage, and protocol downgrade attacks.

## Recommended headers

| Header | Value |
|---|---|
| \`Strict-Transport-Security\` | \`${hsts}\` |
| \`X-Frame-Options\` | \`DENY\` |
| \`X-Content-Type-Options\` | \`nosniff\` |
| \`Referrer-Policy\` | \`strict-origin-when-cross-origin\` |
| \`Permissions-Policy\` | \`${perms}\` |
| \`Content-Security-Policy\` | \`${csp}\` |

---

## How to apply (pick your deployment platform)

### Vercel

Create or update \`vercel.json\` in your project root:

\`\`\`json
{
  "headers": [
    {
      "source": "/(.*)",
      "headers": [
        { "key": "X-Frame-Options", "value": "DENY" },
        { "key": "X-Content-Type-Options", "value": "nosniff" },
        { "key": "Referrer-Policy", "value": "strict-origin-when-cross-origin" },
        { "key": "Permissions-Policy", "value": "${perms}" },
        { "key": "Strict-Transport-Security", "value": "${hsts}" },
        { "key": "Content-Security-Policy", "value": "${csp}" }
      ]
    }
  ]
}
\`\`\`

---

### Netlify

Create or update \`public/_headers\` (or \`_headers\` in your publish directory):

\`\`\`
/*
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: ${perms}
  Strict-Transport-Security: ${hsts}
  Content-Security-Policy: ${csp}
\`\`\`

---

### Cloudflare Pages

In your Cloudflare Dashboard, go to **Rules → Transform Rules → Managed Transforms**,
or add these via the \`cloudflare.toml\` / \`_headers\` file:

\`\`\`
/*
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: ${perms}
  Strict-Transport-Security: ${hsts}
  Content-Security-Policy: ${csp}
\`\`\`

---

### Nginx

Add to your server block \`/etc/nginx/sites-available/your-site\`:

\`\`\`nginx
add_header X-Frame-Options "DENY" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Referrer-Policy "strict-origin-when-cross-origin" always;
add_header Permissions-Policy "${perms}" always;
add_header Strict-Transport-Security "${hsts}" always;
add_header Content-Security-Policy "${csp}" always;
\`\`\`

---

### Apache (.htaccess)

Add to your \`.htaccess\` file:

\`\`\`apache
Header always set X-Frame-Options "DENY"
Header always set X-Content-Type-Options "nosniff"
Header always set Referrer-Policy "strict-origin-when-cross-origin"
Header always set Permissions-Policy "${perms}"
Header always set Strict-Transport-Security "${hsts}"
Header always set Content-Security-Policy "${csp}"
\`\`\`

> **Note**: Requires \`mod_headers\` to be enabled (\`a2enmod headers\`).

---

### Manual / Other

If using a custom server (Express, Fastify, Hono, etc.), install the
corresponding helmet-like middleware and configure these header values:

| Header | Value |
|---|---|
| \`X-Frame-Options\` | \`DENY\` |
| \`X-Content-Type-Options\` | \`nosniff\` |
| \`Referrer-Policy\` | \`strict-origin-when-cross-origin\` |
| \`Permissions-Policy\` | \`${perms}\` |
| \`Strict-Transport-Security\` | \`${hsts}\` |
| \`Content-Security-Policy\` | \`${csp}\` |

---

## Verification

After applying, check your headers with:
- https://securityheaders.com/
- https://csp-evaluator.withgoogle.com/
`,
  };
}
