/**
 * Security headers generator.
 *
 * Generates the security headers block for next.config.ts (Next.js / Remix)
 * or vercel.json (Vite / other). The user has to MERGE this into their
 * existing config — we don't auto-modify files.
 *
 * Headers:
 *   - Content-Security-Policy: defense against XSS
 *   - Strict-Transport-Security: enforce HTTPS
 *   - X-Frame-Options: prevent clickjacking
 *   - X-Content-Type-Options: prevent MIME sniffing
 *   - Referrer-Policy: limit referrer leakage
 *   - Permissions-Policy: disable unused browser features
 */

import type { Framework } from "../framework";

export interface SecurityHeadersInput {
  framework: Framework;
  /** If true, the user is using Stripe — we allow js.stripe.com in CSP */
  usesPayments?: boolean;
}

export function generateSecurityHeaders(input: SecurityHeadersInput): { path: string; content: string } {
  // CSP that allows Stripe if needed
  const stripeScript = input.usesPayments ? " https://js.stripe.com" : "";
  const stripeFrame = input.usesPayments ? " https://js.stripe.com" : "";
  const stripeConnect = input.usesPayments ? " https://api.stripe.com" : "";

  const csp = `default-src 'self'; script-src 'self' 'unsafe-inline'${stripeScript}; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self'${stripeConnect}; frame-src 'self'${stripeFrame}`;

  if (input.framework === "nextjs" || input.framework === "remix") {
    return {
      path: "next.config.headers.ts",
      content: `import type { NextConfig } from "next";

/**
 * Security headers for ${input.framework === "nextjs" ? "Next.js" : "Remix"}.
 * Auto-generated by ShipReady. To use these, merge this headers() function
 * into your existing next.config.{ts,js,mjs}:
 *
 *   import { securityHeaders } from "./next.config.headers";
 *
 *   const nextConfig: NextConfig = {
 *     ...yourOtherConfig,
 *     async headers() {
 *       return [...yourOtherHeaders, ...securityHeaders()];
 *     },
 *   };
 */
export function securityHeaders() {
  return [
    {
      source: "/:path*",
      headers: [
        { key: "X-Frame-Options",         value: "DENY" },
        { key: "X-Content-Type-Options",  value: "nosniff" },
        { key: "Referrer-Policy",         value: "strict-origin-when-cross-origin" },
        { key: "Permissions-Policy",      value: "camera=(), microphone=(), geolocation=(), payment=()" },
        { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
        {
          key: "Content-Security-Policy",
          value: "${csp}",
        },
      ],
    },
  ];
}
`,
    };
  }

  // Vite / other — vercel.json
  return {
    path: "vercel.headers.json",
    content: `{
  "headers": [
    {
      "source": "/(.*)",
      "headers": [
        { "key": "X-Frame-Options", "value": "DENY" },
        { "key": "X-Content-Type-Options", "value": "nosniff" },
        { "key": "Referrer-Policy", "value": "strict-origin-when-cross-origin" },
        { "key": "Permissions-Policy", "value": "camera=(), microphone=(), geolocation=(), payment=()" },
        { "key": "Strict-Transport-Security", "value": "max-age=63072000; includeSubDomains; preload" },
        { "key": "Content-Security-Policy", "value": "${csp}" }
      ]
    }
  ]
}
`,
  };
}
