/**
 * Sitemap generator.
 *
 * Generates a framework-aware sitemap:
 *   - Next.js / Remix: app/sitemap.ts using MetadataRoute.Sitemap
 *   - Astro:           src/pages/sitemap.xml.ts
 *   - Vite / SvelteKit / unknown: public/sitemap.xml (static)
 *
 * The generated sitemap is a starting point — it includes the homepage,
 * /pricing, /about, /blog, /privacy, /terms. Users can extend it with
 * their actual routes.
 */

import type { Framework } from "../framework";
import { frameworkPaths } from "../framework";

export interface SitemapInput {
  framework: Framework;
  /** Site URL, e.g. "https://myapp.com" */
  siteUrl: string;
  /** Project name (used in route comments) */
  projectName: string;
}

export function generateSitemap(input: SitemapInput): { path: string; content: string } {
  const paths = frameworkPaths(input.framework);
  const base = input.siteUrl.replace(/\/$/, "");

  // Next.js / Remix
  if (paths.sitemap === "app/sitemap.ts") {
    return {
      path: "app/sitemap.ts",
      content: `import type { MetadataRoute } from "next";

/**
 * Sitemap for ${input.projectName}.
 * Auto-generated by ShipReady. Add your dynamic routes (blog posts, products, etc.)
 * to the \`routes\` array below.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const base = "${base}";
  const now = new Date();
  const routes: Array<{ path: string; changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"]; priority: number }> = [
    { path: "/",        changeFrequency: "weekly",  priority: 1.0 },
    { path: "/pricing", changeFrequency: "weekly",  priority: 0.9 },
    { path: "/about",   changeFrequency: "monthly", priority: 0.7 },
    { path: "/blog",    changeFrequency: "daily",   priority: 0.8 },
    { path: "/privacy", changeFrequency: "yearly",  priority: 0.4 },
    { path: "/terms",   changeFrequency: "yearly",  priority: 0.4 },
  ];

  return routes.map((r) => ({
    url: \`\${base}\${r.path}\`,
    lastModified: now,
    changeFrequency: r.changeFrequency,
    priority: r.priority,
  }));
}
`,
    };
  }

  // Astro
  if (paths.sitemap === "src/pages/sitemap.xml.ts") {
    return {
      path: "src/pages/sitemap.xml.ts",
      content: `import type { APIRoute } from "astro";

/**
 * Sitemap for ${input.projectName}.
 * Auto-generated by ShipReady.
 */
export const GET: APIRoute = () => {
  const base = "${base}";
  const now = new Date().toISOString();
  const routes = ["/", "/pricing", "/about", "/blog", "/privacy", "/terms"];

  const urls = routes
    .map(
      (r) =>
        \`  <url>\n    <loc>\${base}\${r}</loc>\n    <lastmod>\${now}</lastmod>\n  </url>\`
    )
    .join("\\n");

  const xml = \`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
\${urls}
</urlset>\`;

  return new Response(xml, { headers: { "Content-Type": "application/xml" } });
};
`,
    };
  }

  // Vite / SvelteKit / unknown — static XML
  return {
    path: "public/sitemap.xml",
    content: `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${base}/</loc>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>${base}/pricing</loc>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>${base}/about</loc>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>${base}/blog</loc>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>${base}/privacy</loc>
    <changefreq>yearly</changefreq>
    <priority>0.4</priority>
  </url>
  <url>
    <loc>${base}/terms</loc>
    <changefreq>yearly</changefreq>
    <priority>0.4</priority>
  </url>
</urlset>
`,
  };
}
