/**
 * Terms of Service generator.
 *
 * Two paths:
 *   1. AI path (when `codebase` is provided and AI is enabled):
 *      - Tailors the terms to the actual repo + project context
 *      - Falls back to the static template on any failure
 *   2. Static path: context-aware based on businessType (SaaS gets
 *      subscription language, ecommerce gets shipping/returns, etc.)
 */

import type { ProjectContext, CodebaseContext } from "../types";
import { deriveRules } from "../context";
import { generateTermsWithAI } from "./_ai-prompts";
import { aiEnabled } from "@/lib/ai";

export interface TermsInput {
  context: ProjectContext;
  projectName: string;
  contactEmail: string;
  effectiveDate?: string;
  governingLaw?: string; // e.g. "the State of California, USA"
  /** Optional: AI-curated codebase context. */
  codebase?: CodebaseContext;
}

export async function generateTerms(input: TermsInput): Promise<string> {
  // AI path
  if (input.codebase && aiEnabled) {
    const aiResult = await generateTermsWithAI({
      projectName: input.projectName,
      contactEmail: input.contactEmail,
      description: input.codebase.description,
      projectContext: input.context,
      codebase: input.codebase,
      effectiveDate: input.effectiveDate,
    });
    if (aiResult.ok) {
      return aiResult.text;
    }
    // Fall through to static
  }

  return generateTermsStatic(input);
}

/**
 * Static (non-AI) terms generator. Always works, no external calls.
 */
export function generateTermsStatic(input: TermsInput): string {
  const ctx = input.context;
  const rules = deriveRules(ctx);
  const date = input.effectiveDate || new Date().toISOString().slice(0, 10);
  const law = input.governingLaw || defaultGoverningLaw(ctx);

  const sections: string[] = [];

  sections.push(`# Terms of Service

_Last updated: ${date}_

These Terms of Service ("Terms") govern your access to and use of **${input.projectName}** (the "Service"). By accessing or using the Service, you agree to be bound by these Terms.

If you do not agree to these Terms, you must not access or use the Service.

> **Disclaimer**: These Terms are generated by ShipReady based on the information you provided. They are a starting point and **not legal advice**. Have a qualified attorney review them before going to production.
`);

  // 1. Accounts
  sections.push(`## 1. Accounts

When you create an account with us, you must provide accurate, complete, and current information. Failure to do so constitutes a breach of these Terms and may result in immediate termination of your account.

You are responsible for safeguarding your password and for any activities or actions under your account. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.`);

  // 2. Use of the Service
  sections.push(generateUseSection(ctx));

  // 3. Subscriptions / Payments (if applicable)
  if (ctx.processesPayments) {
    sections.push(generatePaymentsSection());
  }

  // 4. Refunds (if applicable)
  if (ctx.processesPayments) {
    sections.push(generateRefundsSection());
  }

  // 5. Intellectual Property
  sections.push(`## ${ctx.processesPayments ? "5" : "4"}. Intellectual Property

The Service and its original content, features, and functionality are and will remain the exclusive property of ${input.projectName} and its licensors. The Service is protected by copyright, trademark, and other laws.

You retain ownership of any content you submit, post, or display on or through the Service. By submitting content, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, and display such content in connection with the Service.`);

  // 6. Termination
  const num6 = ctx.processesPayments ? "6" : "5";
  sections.push(`## ${num6}. Termination

We may terminate or suspend your account immediately, without prior notice or liability, for any reason, including (without limitation) if you breach these Terms.

Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service or contact us at **${input.contactEmail}**.`);

  // 7. Limitation of Liability
  const num7 = ctx.processesPayments ? "7" : "6";
  sections.push(`## ${num7}. Limitation of Liability

To the maximum extent permitted by applicable law, in no event shall ${input.projectName}, its directors, employees, partners, agents, suppliers, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation loss of profits, data, use, goodwill, or other intangible losses, resulting from:

- Your access to or use of (or inability to access or use) the Service
- Any conduct or content of any third party on the Service
- Any content obtained from the Service
- Unauthorized access, use, or alteration of your transmissions or content

In no event shall our total liability to you for all claims exceed the amount you have paid us in the past twelve (12) months, or one hundred US dollars (USD 100), whichever is greater.`);

  // 8. Disclaimer
  const num8 = ctx.processesPayments ? "8" : "7";
  sections.push(`## ${num8}. Disclaimer

The Service is provided on an "AS IS" and "AS AVAILABLE" basis, without warranties of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, and non-infringement.

We do not warrant that the Service will be uninterrupted, secure, or error-free, or that defects will be corrected.`);

  // 9. Changes
  const num9 = ctx.processesPayments ? "9" : "8";
  sections.push(`## ${num9}. Changes to These Terms

We reserve the right to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days' notice before any new terms take effect. What constitutes a material change will be determined at our sole discretion.

By continuing to access or use the Service after any revisions become effective, you agree to be bound by the revised terms.`);

  // 10. Governing Law
  const num10 = ctx.processesPayments ? "10" : "9";
  sections.push(`## ${num10}. Governing Law

These Terms shall be governed and construed in accordance with the laws of **${law}**, without regard to its conflict of law provisions.

${rules.dataSubjectRights ? "Nothing in these Terms affects your rights as a data subject under the GDPR or UK GDPR." : ""}

Any disputes arising under or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts located in ${law}.`);

  // 11. Contact
  const num11 = ctx.processesPayments ? "11" : "10";
  sections.push(`## ${num11}. Contact Us

If you have any questions about these Terms, please contact us at:

**Email**: ${input.contactEmail}`);

  sections.push(`---

_Generated by [ShipReady](https://shipready.dev) · This is a template, not legal advice._`);

  return sections.join("\n\n---\n\n");
}

function defaultGoverningLaw(ctx: ProjectContext): string {
  switch (ctx.region) {
    case "us": return "the State of Delaware, United States";
    case "eu": return "the Republic of Ireland";
    case "uk": return "England and Wales";
    case "ca": return "the Province of Ontario, Canada";
    case "au": return "New South Wales, Australia";
    default: return "the jurisdiction in which our company is registered";
  }
}

function generateUseSection(ctx: ProjectContext): string {
  let section = `## 2. Use of the Service

You agree to use the Service only for lawful purposes and in accordance with these Terms. Specifically, you agree **not** to:

- Use the Service in any way that violates applicable law or regulation
- Attempt to gain unauthorized access to the Service or related systems
- Interfere with or disrupt the Service or servers connected to the Service
- Use the Service to transmit viruses, malware, or other harmful code
- Reverse engineer, decompile, or attempt to extract the source code of the Service
- Collect or harvest any personal data from the Service
- Impersonate or attempt to impersonate ${ctx.businessType === "saas" ? "the Company, a Company employee, or another user" : "us or any other person or entity"}
- Use the Service in any way that could disable, overburden, damage, or impair the Service`;

  if (ctx.businessType === "ecommerce") {
    section += `
- Submit false or fraudulent orders
- Use the Service to engage in any commercial activity not expressly permitted`;
  }

  return section;
}

function generatePaymentsSection(): string {
  return `## 3. Subscriptions and Payments

Some features of the Service are offered on a subscription basis. By choosing a subscription, you agree to pay the applicable subscription fees as displayed at the time of purchase.

**Billing**: Subscription fees are billed in advance on a recurring basis (monthly or annually, as selected). Your subscription will automatically renew at the end of each billing cycle unless you cancel before the renewal date.

**Price changes**: We may change subscription prices from time to time. We will provide at least 30 days' notice before any price change takes effect. Continued use of the Service after the price change constitutes your agreement to the new price.

**Failed payments**: If a payment fails, we may suspend or terminate your access to paid features until payment is successfully processed.

**Taxes**: Subscription fees are exclusive of any applicable taxes. You are responsible for paying all taxes associated with your subscription.`;
}

function generateRefundsSection(): string {
  return `## 4. Refunds

We want you to be satisfied with the Service. If you are not satisfied, you may request a refund within **14 days** of your initial purchase by contacting us at the email address provided in the Contact section.

After the 14-day period, subscription fees are non-refundable except where required by applicable law. We may, at our sole discretion, offer prorated refunds in cases of extended service outages or other exceptional circumstances.`;
}
