/**
 * Core types for the ShipReady engine.
 * Shared between engine/ (Node) and app/ (Next.js).
 */

export type Severity = "critical" | "recommended" | "optional";

export type IssueStatus = "missing" | "present" | "warning";

export type BusinessType = "saas" | "ecommerce" | "blog" | "portfolio" | "other";

export type Region = "us" | "eu" | "uk" | "ca" | "au" | "global";

/**
 * The 5 context questions. Each one unlocks specific scanners, generators,
 * and template variants. The goal: generate policy text that matches the
 * actual product, not a generic "we collect data" boilerplate.
 */
export interface ProjectContext {
  /** Does the product collect user emails? (sign-up, newsletter, contact form) */
  collectsEmails: boolean;
  /** Does the product process payments? (Stripe, Paddle, LemonSqueezy, etc.) */
  processesPayments: boolean;
  /** Does the product serve users in the EU/EEA/UK? (triggers GDPR) */
  servesEuUsers: boolean;
  /** Does the product use cookies? (analytics, auth, ads, etc.) */
  usesCookies: boolean;
  /** What kind of product is this? */
  businessType: BusinessType;
  /** Primary jurisdiction for legal text */
  region: Region;
}

/**
 * A single issue found by a scanner.
 */
export interface Issue {
  /** Stable identifier, e.g. "missing-privacy-policy" */
  id: string;
  /** Scanner category, e.g. "legal", "secrets", "license" */
  category: "legal" | "secrets" | "license" | "seo" | "errors" | "security" | "meta" | "a11y" | "broken-links" | "performance";
  /** Human-readable title */
  title: string;
  /** 1-2 sentence description of what's wrong and why it matters */
  description: string;
  /** Severity classification */
  severity: Severity;
  /** Current status: missing (not found), present (good), warning (incomplete) */
  status: IssueStatus;
  /** Optional path to the file in the repo that triggered this issue */
  file?: string;
  /** Optional line number */
  line?: number;
  /** If status === "present", the path of the existing file */
  existingFile?: string;
}

/**
 * A generated fix for an issue. The engine produces a list of these.
 */
export interface Fix {
  /** Path where the file should be written, relative to repo root */
  path: string;
  /** Full file contents (string for text, Buffer for binary like images) */
  content: string | Buffer;
  /** Description of what this file does */
  description: string;
  /** The issue this fix resolves */
  issueId: string;
  /** Whether this is a new file (true) or a modification (false) */
  isNew: boolean;
  /** Whether this fix was generated by AI (tailored to the repo) or
   *  by the static template. The UI uses this to show an "AI" badge. */
  generationMode?: "ai" | "static";
  /** When AI-generated, the model that produced it (e.g. "MiniMax-M3"). */
  model?: string;
}

/**
 * The result of a scan.
 */
export interface ScanResult {
  /** Unique scan ID (for /scan/[id] URLs) */
  id: string;
  /** Repo info */
  repo: {
    owner: string;
    name: string;
    defaultBranch: string;
    commitSha: string;
    fileCount: number;
    /** Detected framework (nextjs, vite, astro, remix, sveltekit, unknown) */
    framework: import("./framework").Framework;
    /** Detection confidence: high = config file matched, medium = dir matched */
    frameworkConfidence: "high" | "medium" | "low";
  };
  /** The context the user provided */
  context: ProjectContext;
  /** Issues found, sorted by severity (critical first) */
  issues: Issue[];
  /** The score, 0-100 */
  score: number;
  /** When the scan was run */
  scannedAt: string;
  /** How long the scan took in ms */
  durationMs: number;
  /** True if AI generation is enabled (env has a key). The UI uses this
   *  to show an "AI mode" badge and decide which flow to render. */
  aiEnabled?: boolean;
}

/**
 * A list of files in the repo (recursive). We use this to decide what to scan.
 */
export interface RepoFile {
  path: string;
  type: "file" | "dir";
  size?: number;
  /** Only populated when content is fetched */
  content?: string;
  /** Last commit SHA that touched this file */
  sha?: string;
}

/**
 * Result of fetching the file tree.
 */
export interface RepoTree {
  owner: string;
  name: string;
  defaultBranch: string;
  commitSha: string;
  files: RepoFile[];
}

/**
 * A curated, AI-ready snapshot of a repo's "vibe" — inferred project
 * metadata + snippets of existing copy + a route inventory.
 *
 * Built by `buildCodebaseContext()` (see `engine/src/codebase-context.ts`).
 * Consumed by the AI-powered generators in commit 3+ to produce
 * content that actually matches the repo instead of generic templates.
 */
export interface CodebaseContext {
  /** Repo identity */
  repoOwner: string;
  repoName: string;
  repoUrl: string;
  defaultBranch: string;
  commitSha: string;

  /** Inferred project metadata. All fields have safe fallbacks. */
  projectName: string;        // "shipready" — kebab/snake from package.json or repo
  projectDisplayName: string;  // "ShipReady" — title-cased for humans
  description: string;         // 1-line from README/package.json
  contactEmail: string;        // best guess: existing policy > package author > generated
  brandColor: string;          // hex like "#c4f542"; tasteful default if not found
  siteUrl: string;             // https URL; package.json homepage, or repo-name.com
  region: "us" | "eu" | "uk" | "ca" | "au" | "global";  // best guess from URL TLD / locale

  /** Existing copy on the repo, for tone/style matching. */
  existingCopy: {
    readmeSnippet: string;                                // first 2000 chars
    existingPolicies: Record<string, string>;             // path → first 500 chars
  };

  /** Route inventory derived from the file tree (no file contents fetched for these). */
  pages: string[];                // e.g. ["/", "/pricing", "/about", "/blog"]
  components: string[];           // component file basenames
  packageManager: "npm" | "pnpm" | "yarn" | "bun";
  hasTests: boolean;
  hasCI: boolean;
  framework: import("./framework").Framework;

  /** Diagnostic: which files we actually read. */
  sources: {
    readme: string | null;         // path that was used
    packageJson: string | null;
    layout: string | null;         // root layout / index.html
  };

  /** When the context was built. */
  builtAt: string;
}
