/**
 * Build a ZIP file from a list of fixes.
 * Uses JSZip (works in both Node and browser).
 */

import JSZip from "jszip";
import type { Fix } from "./types";

export interface BuildZipOptions {
  fixes: Fix[];
  /** Repo name, used to make the ZIP filename */
  repoName: string;
  /** Optional: include a README explaining what ShipReady did */
  includeReadme?: boolean;
}

export async function buildFixesZip({
  fixes,
  repoName,
  includeReadme = true,
}: BuildZipOptions): Promise<Blob> {
  const zip = new JSZip();

  for (const fix of fixes) {
    if (Buffer.isBuffer(fix.content)) {
      zip.file(fix.path, fix.content, { binary: true });
    } else {
      zip.file(fix.path, fix.content);
    }
  }

  if (includeReadme) {
    const readme = generateZipReadme(fixes, repoName);
    zip.file("SHIPREADY-README.md", readme);
  }

  return await zip.generateAsync({ type: "blob" });
}

function generateZipReadme(fixes: Fix[], repoName: string): string {
  const lines: string[] = [];
  lines.push(`# ShipReady — Generated Fixes for ${repoName}`);
  lines.push("");
  lines.push(`This ZIP contains ${fixes.length} file${fixes.length === 1 ? "" : "s"} that ShipReady generated to bring your repository closer to production-ready.`);
  lines.push("");
  lines.push("## How to use");
  lines.push("");
  lines.push("1. Extract this ZIP somewhere outside your repo");
  lines.push("2. Copy the files into your repo, preserving the directory structure");
  lines.push("3. Review each file before committing (especially legal documents)");
  lines.push("4. Customize the placeholders (your project name, contact email, etc.)");
  lines.push("5. Commit, push, deploy");
  lines.push("");
  lines.push("## Files included");
  lines.push("");
  for (const fix of fixes) {
    const tag = fix.isNew ? "✨ new" : "✏️ modified";
    lines.push(`- \`${fix.path}\` — ${tag} — ${fix.description}`);
  }
  lines.push("");
  lines.push("## Important");
  lines.push("");
  lines.push("**These files are starting points, not legal advice.** Before going to production, have a qualified attorney review any legal documents (privacy policy, terms, etc.) for your specific jurisdiction and business model.");
  lines.push("");
  lines.push("---");
  lines.push("_Generated by [ShipReady](https://shipready.dev) — the pre-launch checklist for vibe coded websites._");
  return lines.join("\n");
}
